In [2]:
import pandas as pd

In [5]:
trade_df = pd.read_csv('../data/total_trade.csv', encoding='utf-8-sig')
trade_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 687 entries, 0 to 686
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   기간      687 non-null    object
 1   국가      687 non-null    object
 2   HS코드    687 non-null    float64
 3   품목명     687 non-null    object
 4   수출 중량   687 non-null    int64
 5   수출 금액   687 non-null    int64
 6   수입 중량   687 non-null    int64
 7   수입 금액   687 non-null    int64
 8   무역수지    687 non-null    int64
dtypes: float64(1), int64(5), object(3)
memory usage: 48.4+ KB

In [ ]:
# 무역 데이터 상위 5개 행 확인
trade_df.head()

In [ ]:
# 무역 데이터 기초 통계량 확인
trade_df.describe()

In [8]:
# reuter 뉴스 데이터 불러오기
reuter_df = pd.read_csv('../data/reuters.csv', encoding='utf-8-sig')
reuter_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37172 entries, 0 to 37171
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   url        37172 non-null  object
 1   date       37172 non-null  object
 2   title      37172 non-null  object
 3   main_text  37161 non-null  object
dtypes: object(4)
memory usage: 1.1+ MB

In [9]:
# 뉴스 데이터 상위 5개 행 확인
reuter_df.head()

,url,date,title,main_text
0,https://www.reuters.com/breakingviews/abrdn-an...,2024-01-24 12:58:24,Abrdn anguish has no clear M&A endgame,(The author is a Reuters Breakingviews columni...
1,https://www.reuters.com/breakingviews/abu-dhab...,2024-01-26 07:02:43,Abu Dhabi’s Europe M&A hedges an opaque future,"LONDON, Jan 26 (Reuters Breakingviews) - Sulta..."
2,https://www.reuters.com/breakingviews/adani-is...,2024-02-14 03:52:25,Adani is a gift that will keep on giving,"BENGALURU, Feb 14 (Reuters Breakingviews) - Ga..."
3,https://www.reuters.com/breakingviews/ai-start...,2024-01-09 15:28:49,"AI startups’ key challenge is creativity, not ...","NEW YORK, Jan 9 (Reuters Breakingviews) - Deve..."
4,https://www.reuters.com/breakingviews/ai-will-...,2024-05-30 12:46:05,AI will power up buyout barons’ green-energy s...,Renewable energy producers like Neoen have tak...

In [ ]:
# 뉴스 데이터 기초 통계량 확인
reuter_df.describe()

In [3]:
#BBC
bbc_df = pd.read_csv('../data/BBC_title.csv', encoding='utf-8-sig')
bbc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3024 entries, 0 to 3023
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  3024 non-null   object
 1   Headline              2876 non-null   object
 2   Source                3024 non-null   object
 3   Market_Event          3024 non-null   object
 4   Market_Index          3024 non-null   object
 5   Index_Change_Percent  2863 non-null   float64
 6   Trading_Volume        3024 non-null   float64
 7   Sentiment             2853 non-null   object
 8   Sector                3024 non-null   object
 9   Impact_Level          3024 non-null   object
 10  Related_Company       3024 non-null   object
 11  News_Url              2871 non-null   object
dtypes: float64(2), object(10)
memory usage: 283.6+ KB

In [10]:
#acled
acled_df = pd.read_csv('../data/ACLED_data.csv', encoding='utf-8-sig')
acled_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44686 entries, 0 to 44685
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   event_id_cnty       44686 non-null  object
 1   event_date          44686 non-null  object
 2   year                44686 non-null  int64
 3   time_precision      44686 non-null  int64
 4   disorder_type       44686 non-null  object
 5   event_type          44686 non-null  object
 6   sub_event_type      44686 non-null  object
 7   actor1              44686 non-null  object
 8   assoc_actor_1       32046 non-null  object
 9   inter1              44686 non-null  object
 10  actor2              2377 non-null   object
 11  assoc_actor_2       1097 non-null   object
 12  inter2              2377 non-null   object
 13  interaction         44686 non-null  object
 14  civilian_targeting  997 non-null    object
 15  iso                 44686 non-null  int64
 16  region              44686 non-null  object
 17  country             44686 non-null  object
 18  admin1              44558 non-null  object
 19  admin2              42655 non-null  object
 20  admin3              7310 non-null   object
 21  location            44686 non-null  object
 22  latitude            44686 non-null  float64
 23  longitude           44686 non-null  float64
 24  geo_precision       44686 non-null  int64
 25  source              44686 non-null  object
 26  source_scale        44686 non-null  object
 27  notes               44686 non-null  object
 28  fatalities          44686 non-null  int64
 29  tags                43115 non-null  object
 30  timestamp           44686 non-null  int64
dtypes: float64(2), int64(6), object(23)
memory usage: 10.6+ MB

In [11]:
acled_df.head()

,event_id_cnty,event_date,year,time_precision,disorder_type,event_type,sub_event_type,actor1,assoc_actor_1,inter1,...,location,latitude,longitude,geo_precision,source,source_scale,notes,fatalities,tags,timestamp
0,CHN9323,2021-01-01,2021,1,Demonstrations,Protests,Peaceful protest,Protesters (China),Government of China (2017-) Hong Kong Special ...,Protesters,...,Hong Kong - Kwai Tsing,22.3674,114.1329,1,Radio Free Asia; HK01,Subnational-International,"On 1 January 2021, seven district councillors ...",0,crowd size=7,1611094731
1,CHN9328,2021-01-01,2021,1,Demonstrations,Protests,Peaceful protest,Protesters (China),ADPL: Hong Kong Association for Democracy and ...,Protesters,...,Hong Kong - Sham Shui Po,22.3289,114.1586,1,Apple Daily Hong Kong,Subnational,"On 1 January 2021, ADPL district councillors p...",0,crowd size=no report,1611094731
2,CHN9327,2021-01-01,2021,1,Demonstrations,Protests,Peaceful protest,Protesters (China),Five Demands Movement,Protesters,...,Hong Kong - Yau Tsim Mong,22.3201,114.1692,1,Apple Daily Hong Kong,Subnational,"On 1 January 2021, citizens shouted anti-ELAB ...",0,crowd size=no report,1611094731
3,CHN9324,2021-01-01,2021,1,Demonstrations,Protests,Peaceful protest,Protesters (China),NaN,Protesters,...,Hong Kong - North,22.4924,114.1387,1,Ming Pao,Subnational,"On 1 January 2021, citizens protested at the L...",0,crowd size=no report,1611094734
4,CHN9325,2021-01-01,2021,1,Demonstrations,Protests,Peaceful protest,Protesters (China),HKCTU: Hong Kong Confederation of Trade Unions...,Protesters,...,Hong Kong - Sai Kung,22.3070,114.2605,1,Radio Free Asia,International,"On 1 January 2021, HKCTU and Hong Kong Labour ...",0,crowd size=no report,1611094734